compatibility_date = "2021-12-30"
name = "mongo-realm-worker"
type = "javascript"

account_id = "34d053cab64b960a71dfcea2b9371cdf" 
workers_dev = true # or zone_id = "<ZONE ID>" if you have one

[build]
command = "npm run build"

[build.upload]
dir = "build"
main = "./index.mjs"
format = "modules"

[vars]
REALM_APPID = "cloudflare-0-oegtk"

